"""Кто мы для второго компьютера: постоянный идентификатор и сертификат.

Доверие в этой подсистеме держится на отпечатке сертификата, а не на сроке
действия и не на цепочке подписей, поэтому сертификат самоподписанный и живёт
десять лет. Истёкший сертификат означал бы, что связь между двумя спаренными
компьютерами однажды молча перестала работать по календарю.

Если хотя бы одного из трёх файлов идентичности нет на диске, идентичность
создаётся заново целиком, а не достраивается. Это означает, что отпечаток
меняется, и ранее спаренная машина перестанет принимать соединение, потребуя
повторного парринга. Это осознанный выбор в пользу отказа, а не в пользу
молчаливого продолжения с несогласованной парой.

То же самое происходит, если все три файла на месте, но не образуют
согласованную тройку: обрыв процесса между тремя последовательными записями
(выключение питания, снятие процесса, ошибка диска) может оставить на диске,
например, новый ключ со старым сертификатом. Такая тройка не проверяется
атомарностью записи — она проверяется при чтении: ключ должен соответствовать
открытому ключу в сертификате, идентификатор из отдельного файла должен
совпадать с тем, что записан в сертификате, а сам сертификат должен
разбираться. Любое расхождение или повреждение любого из трёх файлов
приводит к тому же исходу, что и отсутствующий файл, — идентичность
пересоздаётся целиком. Файл идентификатора при этом всегда пишется
последним, поэтому его отсутствие само по себе — самый дешёвый признак
незавершённой записи.
"""

from __future__ import annotations

import datetime
import hashlib
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

KEY_FILE_NAME = "node-key.pem"
CERTIFICATE_FILE_NAME = "node-cert.pem"
ORIGIN_FILE_NAME = "node-id.txt"

CERTIFICATE_YEARS = 10


@dataclass(frozen=True)
class NodeIdentity:
    """Постоянное имя этого узла и ключ, которым он себя доказывает."""

    origin_id: str
    certificate_pem: bytes = field(repr=False)
    key_pem: bytes = field(repr=False)

    @property
    def fingerprint(self) -> str:
        return fingerprint_of(self.certificate_pem)


def fingerprint_of(certificate_pem: bytes) -> str:
    """SHA-256 сертификата в DER — то, что закрепляется при парринге."""
    certificate = x509.load_pem_x509_certificate(certificate_pem)
    der = certificate.public_bytes(serialization.Encoding.DER)
    return hashlib.sha256(der).hexdigest()


def load_or_create(directory: Path) -> NodeIdentity:
    """Прочитать идентичность из каталога, создав её при первом обращении."""
    directory.mkdir(parents=True, exist_ok=True)
    key_path = directory / KEY_FILE_NAME
    certificate_path = directory / CERTIFICATE_FILE_NAME
    origin_path = directory / ORIGIN_FILE_NAME

    if key_path.is_file() and certificate_path.is_file() and origin_path.is_file():
        identity = _read_if_consistent(key_path, certificate_path, origin_path)
        if identity is not None:
            return identity
        # Тройка файлов есть, но не образует согласованную идентичность:
        # обрыв записи между файлами, подмена одного из них или порча
        # любого из них выглядят отсюда одинаково. Пересоздаём идентичность
        # целиком — тот же осознанный выбор в пользу отказа, что и при
        # отсутствующем файле, см. docstring модуля.

    return _create_and_persist(key_path, certificate_path, origin_path)


def _read_if_consistent(
    key_path: Path, certificate_path: Path, origin_path: Path
) -> NodeIdentity | None:
    """Вернуть идентичность, только если все три файла образуют согласованную тройку.

    Согласованность означает: все файлы читаются и разбираются, приватный
    ключ соответствует открытому ключу сертификата, а идентификатор из
    отдельного файла совпадает с тем, что записан в общем имени субъекта
    сертификата. Любое расхождение возвращает None, не поднимая исключение,
    — вызывающая сторона обязана пересоздать идентичность.
    """
    try:
        key_pem = key_path.read_bytes()
        key = serialization.load_pem_private_key(key_pem, password=None)
        certificate_pem = certificate_path.read_bytes()
        certificate = x509.load_pem_x509_certificate(certificate_pem)
        origin_id = origin_path.read_text("ascii").strip()
    except ValueError:
        # Повреждённый PEM (ключа или сертификата) либо не-ASCII байты в
        # файле идентификатора — UnicodeDecodeError является подклассом
        # ValueError.
        return None

    if not isinstance(key, rsa.RSAPrivateKey):
        # Qt's Windows Schannel backend cannot import the EC private keys
        # generated by older builds. Treat one as an unusable identity and
        # rotate all three files together, which deliberately requires
        # pairing again rather than leaving sharing permanently offline.
        return None

    if key.public_key().public_numbers() != certificate.public_key().public_numbers():
        # Ключ и сертификат не образуют пару — например, ключ был
        # перезаписан новой генерацией, а сертификат остался от прежней.
        return None

    common_names = certificate.subject.get_attributes_for_oid(NameOID.COMMON_NAME)
    if [attribute.value for attribute in common_names] != [f"Duo Input {origin_id}"]:
        # Идентификатор в отдельном файле разошёлся с тем, что записан в
        # сертификате: одна из двух записей — от другой попытки.
        return None

    return NodeIdentity(origin_id=origin_id, certificate_pem=certificate_pem, key_pem=key_pem)


def _create_and_persist(
    key_path: Path, certificate_path: Path, origin_path: Path
) -> NodeIdentity:
    """Сгенерировать новую идентичность и сохранить её на диск."""
    origin_id = uuid.uuid4().hex
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, f"Duo Input {origin_id}")])
    now = datetime.datetime.now(datetime.UTC)
    certificate = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - datetime.timedelta(days=1))
        .not_valid_after(now + datetime.timedelta(days=365 * CERTIFICATE_YEARS))
        .sign(key, hashes.SHA256())
    )

    key_pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    certificate_pem = certificate.public_bytes(serialization.Encoding.PEM)

    # Идентификатор пишем последним: его отсутствие само по себе означает
    # незавершённую запись, и это самый дешёвый признак рассогласованной
    # тройки при следующем чтении.
    key_path.write_bytes(key_pem)
    certificate_path.write_bytes(certificate_pem)
    origin_path.write_text(origin_id, "ascii")

    return NodeIdentity(origin_id=origin_id, certificate_pem=certificate_pem, key_pem=key_pem)


__all__ = [
    "CERTIFICATE_FILE_NAME",
    "KEY_FILE_NAME",
    "ORIGIN_FILE_NAME",
    "NodeIdentity",
    "fingerprint_of",
    "load_or_create",
]
